[WIP] Tmdb dump initial version
confleux/movie-recommender pull request #1
Opened 2024-10-01 18:03 UTC by confleux

Currently need testing

2024-10-01 18:57 UTC, nikitakosatka requested changes

2024-10-01 18:57 UTC, nikitakosatka commented on tmdb-dump/.gitignore
заменить бы на темплейт гошного гитигнора

2024-10-01 18:57 UTC, nikitakosatka commented on tmdb-dump/cmd/tmdb_dump/main.go
> +	"tmdb-dump/internal/service"
импорты разделяются ньюлайнами, сначала идут стандартная библиотека, потом внешние пакеты, потом внутренние

2024-10-01 18:57 UTC, nikitakosatka commented on tmdb-dump/cmd/tmdb_dump/main.go
> +		time.Sleep(2 * time.Second) // We avoid 429
1) не нужно использовать непрерываемый слип, вместо этого нужно использовать time.After или time.Ticker
2) Нужно использовать exponential backoff для увеличения количества секунд

2024-10-01 18:57 UTC, nikitakosatka commented on tmdb-dump/cmd/tmdb_dump/main.go
> +	for i := 1; i < 10; i++ {
надо отрефачить, убрать меджик намберс и вообще брать из апи количество страниц

2024-10-01 18:57 UTC, nikitakosatka commented on tmdb-dump/cmd/tmdb_dump/main.go
> +	MovieService := service.NewMovieService(ApiClient)
переменные с маленькой буквы должны быть

2024-10-01 18:57 UTC, nikitakosatka commented on tmdb-dump/internal/api_client/api_client.go
> +		return nil, fmt.Errorf("failed to parse url: %w", err)
когда оборачиваешь ошибку не нужно писать failed to, error и тд, потому что потому что получается что-то типа: failed to...: failed to...: failed to

2024-10-01 18:57 UTC, nikitakosatka commented on tmdb-dump/internal/api_client/api_client.go
> +}
сюда нужно прокидывать хттп клиент, чтобы не делать его каждый раз при запросе

2024-10-01 18:57 UTC, nikitakosatka commented on tmdb-dump/internal/api_client/api_client.go
> +	return res, nil
1) тело запроса нужно закрывать
2) еще нужно делать io.Copy(ioutil.Discard, res.Body), чтобы в случае неудачного запроса не терять tcp коннекшн

2024-10-01 18:57 UTC, nikitakosatka commented on tmdb-dump/internal/db/mongodb/mongo.go
нах монга?

2024-10-01 18:57 UTC, nikitakosatka commented on tmdb-dump/internal/api_client/api_client.go
> +func (ac *ApiClient) Get(endpoint string, queryParams *url.Values) (*http.Response, error) {
апи клиент должен реализовывать методы апи, а не просто гет

2024-10-01 18:57 UTC, nikitakosatka commented on tmdb-dump/internal/service/movie.go
> +	if res.StatusCode != 200 {
http.StatusOk

2024-10-01 18:57 UTC, nikitakosatka commented on tmdb-dump/internal/service/movie.go
> +func (ms *MovieService) FetchMovies(page int) (map[string]interface{}, error) {
возвращать мапу плохая идея, нужно сделать свой тип

2024-10-02 11:10 UTC, confleux commented on tmdb-dump/.gitignore
https://github.com/github/gitignore/blob/main/Go.gitignore ?

2024-10-02 12:17 UTC, nikitakosatka commented on tmdb-dump/.gitignore
дад

2024-10-03 16:24 UTC, confleux commented on tmdb-dump/internal/api_client/api_client.go
> +		return nil, fmt.Errorf("failed to parse url: %w", err)
типа `failed to build http request: %w` -> `building http request: %w`?

2024-10-03 16:26 UTC, confleux commented on tmdb-dump/cmd/tmdb_dump/main.go
> +	for i := 1; i < 10; i++ {
в доке нигде не указан лимит на страницы

2024-10-03 16:31 UTC, confleux commented on tmdb-dump/internal/db/mongodb/mongo.go
temporary 😎😎

2024-10-04 13:30 UTC, nikitakosatka commented on tmdb-dump/internal/api_client/api_client.go
> +		return nil, fmt.Errorf("failed to parse url: %w", err)
даже просто `build http request: %w`

2024-10-13 09:14 UTC, nikitakosatka reviewed
можно еще логгер проиницализировать нормальный какой-нибудь, где есть структурное логгирование

2024-10-13 09:14 UTC, nikitakosatka commented on tmdb-dump/cmd/tmdb_dump/main.go
> +					}
Fatal не рекомендуется использовать, это по сути os.Exit
если был вызван Fatal, то defer'ы не вызовятся
поэтому лучше завернуть все что есть в мейне в функцию `func run() error` и возвращать из этой функции ошибку, а в фейне уже вызывать функцию run и если вернулась ошибка сделать Fatal

2024-10-13 09:14 UTC, nikitakosatka commented on tmdb-dump/cmd/tmdb_dump/main.go
> +	log.Printf("TMDB Dump took: %s", elapsed)
Info

2024-10-13 09:14 UTC, nikitakosatka commented on tmdb-dump/internal/api_client/api_client.go
> +	if err != nil {
можно в одну строчку

2024-10-13 09:14 UTC, nikitakosatka commented on tmdb-dump/internal/api_client/api_client.go
> +	if err != nil {
тоже в одну строку можно

2024-10-13 09:14 UTC, nikitakosatka commented on tmdb-dump/internal/repository/mongodb/movie.go
> +func (mr *MovieRepository) InsertMoviesPage(moviePage *api_client.GetMoviesResponse) (interface{}, error) {
давай не интерфейс возвращать тут

2024-10-13 09:14 UTC, nikitakosatka commented on tmdb-dump/internal/repository/mongodb/movie.go
> +package mongodb_movie
го пакеты ноукейсом называть, типа mongodbmovie

2024-10-13 09:14 UTC, nikitakosatka commented on tmdb-dump/internal/repository/postgres/movie.go
> +	}
с этим надо чето сделать

2024-10-13 09:51 UTC, confleux commented on tmdb-dump/internal/repository/postgres/movie.go
> +	}
а че можно? я ж не могу рандом дату поставить. по идее, если даты нету, значит она nil, вполне логично получается

2024-10-13 10:48 UTC, nikitakosatka commented on tmdb-dump/internal/repository/postgres/movie.go
> +	}
ну по крайней мере переменную не any сделать

2024-12-09 11:42 UTC, merged